qa/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.decorators.csrf import ensure_csrf_cookie

from accounts import views

urlpatterns = [
    url(r'^admin/',
        include(admin.site.urls)
        ),

    url(r'^accounts/',
        include('allauth.urls')
        ),

    url(r'^questions/',
        include('questions.urls', namespace='questions')
        ),

    url(r'^$',
        ensure_csrf_cookie(TemplateView.as_view(template_name='index.html')),
        name='index'
        ),

    url(r'^accounts/profile/$',
        views.profile_view,
        name='account_profile'
        ),
]

qa/questions/urls.py
from django.conf.urls import url

from . import views
from . import models

urlpatterns = [
    url(r'^create/$',
        views.QuestionCreateView.as_view(),
        name='create',
        ),

    url(r'^$',
        views.QuestionListView.as_view(),
        name='list',
        ),

    url(r'^(?P<pk>[0-9]+)/update/$',
        views.QuestionUpdateView.as_view(),
        name='update',
        ),

    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.QuestionDeleteView.as_view(),
        name='delete',
        ),

    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]*)/$',
        views.QuestionDetailView.as_view(),
        name='details',
        ),

    url(r'^comments/(?P<parent_pk>[0-9]+)/create/$',
        views.CommentCreateView.as_view(parent_model=models.Question),
        name='add_question_comment'
        ),

    url(r'^comments/answers/(?P<parent_pk>[0-9]+)/create/$',
        views.CommentCreateView.as_view(parent_model=models.Answer),
        name='add_answer_comment'
        ),

    url(r'^comments/delete/(?P<pk>[0-9]+)/$',
        views.CommentDeleteView.as_view(),
        name='delete_comment'
        ),

    url(r'^comments/update/(?P<pk>[0-9]+)/$',
        views.CommentUpdateView.as_view(),
        name='update_comment'
        ),

    url(r'^api/$',
        views.QuestionListCreateAPIView.as_view(),
        name='api'
        ),

    url(r'^api/(?P<pk>[0-9]+)$',
        views.QuestionRetrieveUpdateDestroyAPIView.as_view(),
        name='api'
        ),
]

qa/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>
	{% block title %}
	{% block head_title %}{% endblock head_title %}
	| Simple question app |
	{% endblock title %}
</title>

	{% block css %}
	<link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
	{% endblock css %}

	{% block js %}
	<!-- Latest JQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>
	{% endblock js %}

</head>
<body>
	<div class="conteiner">
		<nav class="navbar navbar-dark navbar-static-top bg-inverse">
			<div class="conteiner">
				<a class="navbar-brand" href="{% url 'questions:list' %}">Questions app</a>
				<button type="button" class="navbar-toggler hidden-sm-up pull-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
				&#9776;
				</button>
				<div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
					<ul class="nav navbar-nav pull-right">
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'questions:list' %}">List of questions</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'questions:create' %}">Create question</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'account_login' %}">Log in</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
	</div>
	{% block content %}
	{% endblock content %}
</body>
</html>

qa/templates/index.html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>React Tutorial</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.2/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.2/react-dom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </head>
  <body>
    <div id="content"></div>
    <script type="text/babel">
      // To get started with this tutorial running your own code, simply remove
      // the script tag loading scripts/example.js and start writing code here.

// CSRF protection
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

// REACT

var Question = React.createClass({
  render: function() {
    return (
      <div className="question">
        <h2 className="questionAuthor">
	  {this.props.author}
	</h2>
	{this.props.children}
      </div>
    );
  }
});

var QuestionList = React.createClass({
  render: function() {
    var questionNodes = this.props.data.map(function(question) {
	return (
	  <Question author={question.title}>
	    {question.details}
	  </Question>
	);
    });
    return (
      <div className="questionList">
	{questionNodes}
      </div>
    );
  }
});

var QuestionForm = React.createClass({
  handleSubmit: function(e) {
    e.preventDefault();
    var title = this.refs.title.value.trim();
    var details = this.refs.details.value.trim();
    if (!title) {
      return;
    }
    this.props.onQuestionSubmit({title: title, details: details});
    this.refs.title.value = "";
    this.refs.details.value = "";
    return;
  },
  render: function() {
    return (
      <form className="questionForm" onSubmit={this.handleSubmit}>
	<input type="text" placeholder="Title" ref="title"/>
	<input type="text" placeholder="Details" ref="details"/>
	<input type="submit" value="Post"/>
      </form>
    );
  }
});

var QuestionBox = React.createClass({
  loadQuestionsFromServer: function() {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      cache: 'false',
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  handleQuestionSubmit: function(question) {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      type: 'POST',
      data: question,
      success: function(data) {
        //this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  getInitialState: function() {
    return {data: []}
  },
  componentDidMount: function() {
    this.loadQuestionsFromServer();
    setInterval(this.loadQuestionsFromServer, this.props.pollInterval);
  },
  render: function() {
    return (
      <div className="QuestionBox">
	<h1>Questions</h1>
	<QuestionList data={this.state.data}/>
	<QuestionForm onQuestionSubmit={this.handleQuestionSubmit} />
      </div>
    );
  }
});

ReactDOM.render(
  <QuestionBox url="/questions/api/" pollInterval={2000}/> ,
  document.getElementById('content')
);

    </script>
  </body>
</html>