qa/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.decorators.csrf import ensure_csrf_cookie

from accounts import views

urlpatterns = [
    url(r'^admin/',
        include(admin.site.urls)
        ),

    url(r'^accounts/',
        include('allauth.urls')
        ),

    url(r'^questions/',
        include('questions.urls', namespace='questions')
        ),

    url(r'^$',
        ensure_csrf_cookie(TemplateView.as_view(template_name='index.html')),
        name='index'
        ),

    url(r'^accounts/profile/$',
        views.profile_view,
        name='account_profile'
        ),
]

qa/questions/urls.py
from django.conf.urls import url

from . import views
from . import models

urlpatterns = [
    url(r'^create/$',
        views.QuestionCreateView.as_view(),
        name='create',
        ),

    url(r'^$',
        views.QuestionListView.as_view(),
        name='list',
        ),

    url(r'^(?P<pk>[0-9]+)/update/$',
        views.QuestionUpdateView.as_view(),
        name='update',
        ),

    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.QuestionDeleteView.as_view(),
        name='delete',
        ),

    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]*)/$',
        views.QuestionDetailView.as_view(),
        name='details',
        ),

    url(r'^comments/(?P<parent_pk>[0-9]+)/create/$',
        views.CommentCreateView.as_view(parent_model=models.Question),
        name='add_question_comment'
        ),

    url(r'^comments/answers/(?P<parent_pk>[0-9]+)/create/$',
        views.CommentCreateView.as_view(parent_model=models.Answer),
        name='add_answer_comment'
        ),

    url(r'^comments/delete/(?P<pk>[0-9]+)/$',
        views.CommentDeleteView.as_view(),
        name='delete_comment'
        ),

    url(r'^comments/update/(?P<pk>[0-9]+)/$',
        views.CommentUpdateView.as_view(),
        name='update_comment'
        ),

    url(r'^api/$',
        views.QuestionListCreateAPIView.as_view(),
        name='api'
        ),

    url(r'^api/(?P<pk>[0-9]+)$',
        views.QuestionRetrieveUpdateDestroyAPIView.as_view(),
        name='api'
        ),
]

qa/questions/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
from django.conf import settings

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType


class Comment(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    text = models.TextField()
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    def __str__(self):
        return self.text


class Question(models.Model):
    title = models.CharField(max_length=200)
    details = models.TextField(blank=True)
    slug = models.SlugField(blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    comments = GenericRelation(Comment)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Question, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('questions:details',
                       kwargs={'pk': self.id, 'slug': self.slug})


class Answer(models.Model):
    text = models.TextField()
    question = models.ForeignKey(Question)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    comments = GenericRelation(Comment)

    def get_absolute_url(self):
        return self.question.get_absolute_url()

qa/questions/forms.py
from django.forms import ModelForm
# from django import forms

from .models import Answer


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ("text",)
        # fields = ("text", "question")
        # widgets = {"question": forms.HiddenInput()}

qa/questions/views.py
# from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.views.generic import ListView
# from django.views.decorators.http import require_http_methods
from django.core.urlresolvers import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from rest_framework.generics import ListCreateAPIView
from rest_framework.generics import RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.exceptions import ValidationError

from .models import Question, Answer, Comment
from .forms import AnswerForm
from .serializers import QuestionSerializer
from .decorators import owner_required


class QuestionListView(ListView):
    model = Question


class QuestionCreateView(CreateView):
    model = Question
    fields = ("title", "details")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(QuestionCreateView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuestionCreateView, self).dispatch(*args, **kwargs)


class QuestionUpdateView(UpdateView):
    model = Question
    template_name_suffix = '_update_form'
    fields = ("title", "details")

    @method_decorator(login_required)
    @owner_required
    def dispatch(self, *args, **kwargs):
        return super(QuestionUpdateView, self).dispatch(*args, **kwargs)


class QuestionDeleteView(DeleteView):
    model = Question
    success_url = reverse_lazy('questions:list')

    @method_decorator(login_required)
    @owner_required
    def dispatch(self, *args, **kwargs):
        return super(QuestionDeleteView, self).dispatch(*args, **kwargs)


class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        # for better performance need equivalent of select_relative
        # for answer comments
        context['answers'] = self.object.answer_set.all()
        context['comments'] = self.object.comments.all()
        context['answer_form'] = AnswerForm()
        return context

    @method_decorator(login_required)
    def post(self, request, pk, **kwargs):
        form = AnswerForm(request.POST)
        self.object = self.get_object()
        if form.is_valid():
            answer = Answer(text=form.cleaned_data['text'])
            answer.owner = request.user
            answer.question = self.object
            answer.save()
            return redirect(answer.question)
        context = self.get_context_data()
        context['answer_form'] = form
        return self.render_to_response(context)


class QuestionListCreateAPIView(ListCreateAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class QuestionRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)

    def perform_update(self, serializer):
        instance = serializer.instance
        if instance.owner != self.request.user:
            raise ValidationError("You can update only your own questions")
        serializer.save()

    def perform_destroy(self, instance):
        if instance.owner != self.request.user:
            raise ValidationError("You can destroy only your own questions")
        return super(QuestionRetrieveUpdateDestroyAPIView,
                     self).perform_destroy(instance)


class CommentCreateView(CreateView):
    model = Comment
    fields = ('text',)
    http_method_names = [u'post']
    parent_model = None

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = form_class(request.POST)
        parent_pk = kwargs['parent_pk']
        parent_instance = self.parent_model.objects.get(pk=parent_pk)
        if not parent_instance:
            raise ValidationError("Parent is invalid")
        if form.is_valid():
            form.instance.content_object = parent_instance
            form.instance.owner = request.user
            form.save()
        referer = request.META.get('HTTP_REFERER')
        if referer:
            return redirect(referer)
        return redirect(parent_instance)


class CommentUpdateView(UpdateView):
    model = Comment
    fields = ('text',)
    http_method_names = [u'post']

    def get_success_url(self):
        return self.object.content_object.get_absolute_url()

    @method_decorator(login_required)
    @owner_required
    def dispatch(self, *args, **kwargs):
        return super(CommentUpdateView, self).dispatch(*args, **kwargs)


class CommentDeleteView(DeleteView):
    model = Comment
    http_method_names = [u'post']

    def get_success_url(self):
        return self.object.content_object.get_absolute_url()

    @method_decorator(login_required)
    @owner_required
    def dispatch(self, *args, **kwargs):
        return super(CommentDeleteView, self).dispatch(*args, **kwargs)

qa/templates/questions/answer_form.html
<form action="{% url 'questions:add_answer' %}" method="POST">
{% csrf_token %}
	<table>
		{{ form }}
	</table>
	<input type="submit" value="Add Answer"\>
</form>

qa/templates/questions/question_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Are you sure you want to delete this question?</h1>
<form action="{% url 'questions:delete' question.pk %}" method="POST">
	{% csrf_token %}
	<input type='submit' value="Delete"/>
</form>

{% endblock content %}

qa/templates/questions/question_detail.html
{% extends "base.html" %}

{% block content %}

<div class="conteiner">

<div class="row">
	<div class="col-xs-12">
		<h1 class="text-center">{{ question.title }}</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-9">
		<p class="text-justify">{{ question.details }}</p>
	</div>
	{% if user == question.owner %}
	<div class="col-xs-1 text-right">
		<a class="btn" href="{% url 'questions:update' question.pk %}"> Update</a>
		<form action="{% url 'questions:delete' question.pk %}" method="POST">
			{% csrf_token %}
			<input class="btn" type="submit" value="Delete"/>
		</form>
	</div>
	{% endif %}
</div>
<div class="row">
	<div class="col-xs-12">
		<p class="text-right"><small>Owner: {{ question.owner }}</small></p>
	</div>
</div>

{% for comment in comments %}
	<div class="row">
		<div class="col-xs-offset-1 col-xs-8">
			<p class="text-left">{{ comment }} :-- {{ comment.owner }}</p>
		</div>
		{% if user == comment.owner %}
		<div class="col-xs-3">
			<form action="{% url 'questions:delete_comment' comment.pk %}" method="POST">
				{% csrf_token %}
				<input class="btn btn-sm" type="submit" value="delete" />
			</form>
		</div>
		{% endif %}
	</div>
{% endfor %}

{% if user.is_authenticated %}
<div class="row">
	{# BAD HARDcODED FORM #}
	<div class="col-xs-offset-1 col-xs-8">
	<form action="{% url 'questions:add_question_comment' question.pk %}" method="POST">
		{% csrf_token %}
		<input type="textarea" name="text"/>
		<input class="btn btn-primary" type="submit" value="Add comment"/>
	</form>
	</div>
</div>
{% endif %}

<h2>Answers</h2>

<ul>
{% for answer in answers %}
<li>{{ answer.text }} </li>
<ul>
{% for comment in answer.comments.all %}
<li>
	{{ comment }} :-- {{ comment.owner }}
	{% if user == comment.owner %}
	<form action="{% url 'questions:delete_comment' comment.pk %}" method="POST">
		{% csrf_token %}
		<input type="submit" value="delete" />
	</form>
	{% endif %}
</li>
{% endfor %}

{% if user.is_authenticated %}
<li>
	{# BAD HARDcODED FORM #}
	<form action="{% url 'questions:add_answer_comment' answer.pk %}" method="POST">
		{% csrf_token %}
		<input type="textarea" name="text"/>
		<input type="submit" value="Add comment"/>
	</form>
</li>
{% endif %}
</ul>

{% endfor %}
</ul>

{% if user.is_authenticated %}

<h3>Add your answer</h3>

<form action="" method="POST">
{% csrf_token %}
{{ answer_form.as_p }}
<input type='submit' value='Add answer'/>
</form>

{% endif %}
</div>


</div>
{% endblock content %}

qa/templates/questions/question_form.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'questions:create' %}" method="POST">
	{% csrf_token %}
	<table>
	{{ form }}
	</table>
	<input type="submit" value="Create"/>
</form>
{% endblock content %}

qa/templates/questions/question_list.html
{% extends "base.html" %}

{% block content %}
<div class="conteiner">
	<table class="table table-bordered">
	{% for question in question_list %}
		<tr><td>
			<a href="{% url 'questions:details' question.pk question.slug %}">{{ question.title }}</a>
		</td></tr>
	{% endfor %}
	</table>
</div>
{% endblock content %}

qa/templates/questions/question_update_form.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'questions:update' question.pk %}" method="POST">
	{% csrf_token %}
	<table>
	{{ form }}
	</table>
	<input type="submit" value="Update"/>
</form>
{% endblock content %}